<a href="https://colab.research.google.com/github/px70339sai/Data690_Sai/blob/main/individual_project/Part_B_Draft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

print("Pandas Version is ", pd.__version__)

import plotly 

print("Plotly Version is", plotly.__version__)

import plotly.graph_objects as go
import plotly.express as px

Pandas Version is  1.1.5
Plotly Version is 4.4.1

In [10]:
df = pd.read_csv("https://raw.githubusercontent.com/DATA-690-FALL-2021/Data690_Sai/main/wdi_data%20(6).csv")
df.head()

   Unnamed: 0  Year  ...         Income Group    Lending Type
0           0  2018  ...  Upper middle income            IBRD
1           1  2015  ...          High income  Not classified
2           2  2016  ...          High income  Not classified
3           3  2017  ...          High income  Not classified
4           4  2018  ...          High income  Not classified

[5 rows x 9 columns]

In [11]:
df.drop(columns=["Unnamed: 0"], inplace=True)
df.head()

   Year  value  ...         Income Group    Lending Type
0  2018   25.0  ...  Upper middle income            IBRD
1  2015   19.1  ...          High income  Not classified
2  2016   18.9  ...          High income  Not classified
3  2017   19.3  ...          High income  Not classified
4  2018   18.7  ...          High income  Not classified

[5 rows x 8 columns]

In [12]:
df.sample(10)

     Year      value  ...         Income Group    Lending Type
574  2007   1.226932  ...  Upper middle income            IBRD
349  2017  40.000000  ...  Upper middle income            IBRD
719  2016  20.700000  ...          High income  Not classified
253  2017  33.900000  ...          High income  Not classified
829  2019  30.100000  ...          High income  Not classified
273  2017  27.800000  ...          High income  Not classified
648  2012   0.768917  ...  Upper middle income            IBRD
386  2014   7.816234  ...  Upper middle income            IBRD
438  2005  22.113804  ...  Lower middle income            IBRD
225  2019  17.200000  ...  Upper middle income            IBRD

[10 rows x 8 columns]

In [13]:
df_2000 = df.query("Year == 2020")

df_2000.sample(10)

     Year  value  ...         Income Group    Lending Type
64   2020   15.8  ...          High income  Not classified
661  2020   53.8  ...           Low income             IDA
749  2020   18.0  ...          High income  Not classified
708  2020   12.7  ...          High income  Not classified
85   2020   17.8  ...          High income  Not classified
814  2020   36.1  ...  Upper middle income            IBRD
192  2020   29.8  ...  Upper middle income            IBRD
149  2020   31.9  ...  Upper middle income            IBRD
240  2020   16.2  ...          High income  Not classified
44   2020   16.2  ...          High income  Not classified

[10 rows x 8 columns]

In [14]:
poverty_headcount = pd.read_csv("/content/wdi_data (7).csv")
poverty_headcount.drop(columns=["Unnamed: 0"], inplace=True)
poverty_headcount.head()

   Year      value  ...         Income Group Lending Type
0  2004  16.963144  ...  Upper middle income         IBRD
1  2005  13.317249  ...  Upper middle income         IBRD
2  2006  10.317365  ...  Upper middle income         IBRD
3  2007   8.750589  ...  Upper middle income         IBRD
4  2008   8.210397  ...  Upper middle income         IBRD

[5 rows x 8 columns]

In [15]:
poverty_headcount.columns

Index(['Year', 'value', 'indicator', 'Country Code', 'Country Name', 'Region',
       'Income Group', 'Lending Type'],
      dtype='object')

In [16]:
poverty_headcount_2000 = poverty_headcount.query("Year == 2000")

poverty_headcount_2000 .sample(5)

     Year      value  ...         Income Group Lending Type
35   2000   9.361176  ...          High income         IBRD
96   2000  33.851749  ...  Upper middle income         IBRD
58   2000  15.713312  ...  Upper middle income         IBRD
157  2000   3.583435  ...          High income         IBRD
72   2000  46.441582  ...  Upper middle income         IBRD

[5 rows x 8 columns]

In [17]:
poverty_headcount_2000 = poverty_headcount_2000.query("indicator in ['1.0.HCount.2.5usd']")

poverty_headcount_2000

     Year      value  ...         Income Group Lending Type
11   2000  43.250916  ...  Lower middle income         IBRD
35   2000   9.361176  ...          High income         IBRD
58   2000  15.713312  ...  Upper middle income         IBRD
72   2000  46.441582  ...  Upper middle income         IBRD
96   2000  33.851749  ...  Upper middle income         IBRD
113  2000  19.544781  ...  Upper middle income         IBRD
157  2000   3.583435  ...          High income         IBRD

[7 rows x 8 columns]

In [18]:
df_pivot = poverty_headcount_2000.pivot_table(index=['Country Code','Country Name','Region','Income Group','Lending Type'], columns= 'indicator').reset_index()
df_pivot.head()

          Country Code        Country Name  ...              Year             value
indicator                                   ... 1.0.HCount.2.5usd 1.0.HCount.2.5usd
0                  BOL             Bolivia  ...              2000         43.250916
1                  CHL               Chile  ...              2000          9.361176
2                  DOM  Dominican Republic  ...              2000         15.713312
3                  ECU             Ecuador  ...              2000         46.441582
4                  GTM           Guatemala  ...              2000         33.851749

[5 rows x 7 columns]

In [19]:
fig = px.scatter(
    poverty_headcount_2000.dropna(),
    x="Year",
    y="value",
    title="Poverty Headcount",
    hover_name="Country Name",
    )

fig.show()

In [20]:
Labour_Income_Poverty_Index_2004 = poverty_headcount.query("Year == 2004")
Labour_Income_Poverty_Index_2004

     Year      value  ...         Income Group Lending Type
0    2004  16.963144  ...  Upper middle income         IBRD
26   2004  23.951452  ...  Upper middle income         IBRD
44   2004  28.392906  ...  Upper middle income         IBRD
62   2004  27.766209  ...  Upper middle income         IBRD
74   2004  28.805305  ...  Upper middle income         IBRD
85   2004  21.832012  ...  Lower middle income         IBRD
102  2004  46.768871  ...  Lower middle income          IDA
115  2004  14.729934  ...  Upper middle income         IBRD
135  2004  20.824310  ...  Upper middle income         IBRD
146  2004  25.767765  ...  Upper middle income         IBRD
161  2004   9.780787  ...          High income         IBRD
706  2004   1.420575  ...  Upper middle income         IBRD

[12 rows x 8 columns]

In [21]:
Labour_Income_Poverty_Index_2004 = poverty_headcount_2000.query("indicator in ['1.0.HCount.2.5usd','8.0.LIPI']")

Labour_Income_Poverty_Index_2004

     Year      value  ...         Income Group Lending Type
11   2000  43.250916  ...  Lower middle income         IBRD
35   2000   9.361176  ...          High income         IBRD
58   2000  15.713312  ...  Upper middle income         IBRD
72   2000  46.441582  ...  Upper middle income         IBRD
96   2000  33.851749  ...  Upper middle income         IBRD
113  2000  19.544781  ...  Upper middle income         IBRD
157  2000   3.583435  ...          High income         IBRD

[7 rows x 8 columns]

In [22]:
df_pivot = Labour_Income_Poverty_Index_2004.pivot_table(index=['Country Code','Country Name','Region','Income Group','Lending Type','value'], columns= 'indicator').reset_index()
df_pivot.head(10)

          Country Code        Country Name  ...      value              Year
indicator                                   ...            1.0.HCount.2.5usd
0                  BOL             Bolivia  ...  43.250916              2000
1                  CHL               Chile  ...   9.361176              2000
2                  DOM  Dominican Republic  ...  15.713312              2000
3                  ECU             Ecuador  ...  46.441582              2000
4                  GTM           Guatemala  ...  33.851749              2000
5                  MEX              Mexico  ...  19.544781              2000
6                  URY             Uruguay  ...   3.583435              2000

[7 rows x 7 columns]

In [23]:
fig = px.bar(
    df,
    x="Year",
    y="value",
    title="Labour Income Poverty Index",
    color="Country Name",
     # this is used to show the name when mouse is moved on the dot. 
    #text="Country Name", # text is used to display a name all time. 
    
)


fig.show()

In [24]:
multidimensional_children = pd.read_csv("/content/wdi_data (7).csv")
multidimensional_children.drop(columns=["Unnamed: 0"], inplace=True)
multidimensional_children.head()

   Year      value  ...         Income Group Lending Type
0  2004  16.963144  ...  Upper middle income         IBRD
1  2005  13.317249  ...  Upper middle income         IBRD
2  2006  10.317365  ...  Upper middle income         IBRD
3  2007   8.750589  ...  Upper middle income         IBRD
4  2008   8.210397  ...  Upper middle income         IBRD

[5 rows x 8 columns]

In [26]:
multidimensional_children_data = multidimensional_children.query("indicator in ['1.0.HCount.2.5usd','8.0.LIPI']")

multidimensional_children_data

     Year      value  ...         Income Group Lending Type
0    2004  16.963144  ...  Upper middle income         IBRD
1    2005  13.317249  ...  Upper middle income         IBRD
2    2006  10.317365  ...  Upper middle income         IBRD
3    2007   8.750589  ...  Upper middle income         IBRD
4    2008   8.210397  ...  Upper middle income         IBRD
..    ...        ...  ...                  ...          ...
800  2010   0.998376  ...          High income         IBRD
801  2011   0.832277  ...          High income         IBRD
802  2012   0.786716  ...          High income         IBRD
803  2013   0.778537  ...          High income         IBRD
804  2014   0.760867  ...          High income         IBRD

[271 rows x 8 columns]

In [25]:
df_pivot =multidimensional_children.pivot_table(index=['Country Code','Country Name','Region','Income Group','Lending Type','value'], columns= 'indicator').reset_index()
df_pivot.head(10)

          Country Code Country Name  ...           Year
indicator                            ... SI.POV.MDIM.MA SI.POV.MDIM.XQ
0                  AFG  Afghanistan  ...            NaN         2020.0
1                  AFG  Afghanistan  ...            NaN         2016.0
2                  AFG  Afghanistan  ...            NaN            NaN
3                  AFG  Afghanistan  ...            NaN            NaN
4                  AGO       Angola  ...            NaN         2015.0
5                  AGO       Angola  ...            NaN            NaN
6                  ARG    Argentina  ...            NaN            NaN
7                  ARG    Argentina  ...            NaN            NaN
8                  ARG    Argentina  ...            NaN            NaN
9                  ARG    Argentina  ...            NaN            NaN

[10 rows x 12 columns]

In [27]:
fig = px.bar(
    multidimensional_children_data,
    title = "Multidimensional Poverty Headcount Ratio, Children(% of Population 0-17)",
    labels = {"value":"Poverty Headcount","Year":"YEAR"},
    orientation="v",
    x= 'Year',
    y = 'value'
    
)
fig.update_xaxes(tickangle=45)

fig.show()

In [28]:
multidimensional_male= pd.read_csv("/content/wdi_data (7).csv")
multidimensional_male.drop(columns=["Unnamed: 0"], inplace=True)
multidimensional_male.head()

   Year      value  ...         Income Group Lending Type
0  2004  16.963144  ...  Upper middle income         IBRD
1  2005  13.317249  ...  Upper middle income         IBRD
2  2006  10.317365  ...  Upper middle income         IBRD
3  2007   8.750589  ...  Upper middle income         IBRD
4  2008   8.210397  ...  Upper middle income         IBRD

[5 rows x 8 columns]

In [29]:
multidimensional_male.columns

Index(['Year', 'value', 'indicator', 'Country Code', 'Country Name', 'Region',
       'Income Group', 'Lending Type'],
      dtype='object')

In [31]:
multidimensional_men_data = multidimensional_children.query("indicator in ['SI.POV.MDIM.FE']")

multidimensional_men_data

     Year  value  ...         Income Group    Lending Type
530  2018   25.0  ...  Upper middle income            IBRD
531  2015   19.1  ...          High income  Not classified
532  2016   18.9  ...          High income  Not classified
533  2017   19.3  ...          High income  Not classified
534  2018   18.7  ...          High income  Not classified
..    ...    ...  ...                  ...             ...
701  2015   42.4  ...  Upper middle income            IBRD
702  2016   46.1  ...  Upper middle income            IBRD
703  2017   42.6  ...  Upper middle income            IBRD
704  2018   41.0  ...  Upper middle income            IBRD
705  2019   41.0  ...  Upper middle income            IBRD

[176 rows x 8 columns]

In [33]:
multidimensional_men_data.columns

Index(['Year', 'value', 'indicator', 'Country Code', 'Country Name', 'Region',
       'Income Group', 'Lending Type'],
      dtype='object')

In [36]:
df_pivot =multidimensional_men_data.pivot_table(index=['Country Code','Country Name','Region','Income Group','Lending Type','value'], columns= 'indicator').reset_index()
df_pivot.head(10)

          Country Code Country Name  ... value           Year
indicator                            ...       SI.POV.MDIM.FE
0                  ARM      Armenia  ...  25.0         2018.0
1                  AUT      Austria  ...  18.3         2019.0
2                  AUT      Austria  ...  18.7         2018.0
3                  AUT      Austria  ...  18.9         2016.0
4                  AUT      Austria  ...  19.1         2015.0
5                  AUT      Austria  ...  19.3         2017.0
6                  BEL      Belgium  ...  20.0         2019.0
7                  BEL      Belgium  ...  20.9         2018.0
8                  BEL      Belgium  ...  21.8         2017.0
9                  BEL      Belgium  ...  22.2         2015.0

[10 rows x 7 columns]

In [59]:
fig = go.Figure()

trace_0 = go.Bar(      
    x=df_pivot["Year"],    
    y=df_pivot["value"]
)

fig.add_trace(trace_0)

fig.update_layout(
    title="Multidimensional Poverty Headcount Ratio, Male(% of Male Population",
    xaxis_title="YEAR",
    yaxis_title="Male Poverty Headcount"
)

fig.show()

In [60]:
fig = px.pie(df_pivot, values='SP.POP.TOTL', names='Country Name', title='Total Population',hover_name='Country Name')
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

ValueError: ignored

In [67]:
fig = px.line(
    df_pivot.dropna(),
    x="Year", 
    y="SI.POV.MDIM.FE",
    color='Country Name',
    
)
fig.update_xaxes(type='category')
fig.show()

Exception: ignored