<a href="https://colab.research.google.com/github/px70339sai/Data690_Sai/blob/main/Assignment_08/Assignment_08_Inclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
import plotly.express as px

In [45]:
df= pd.read_csv("/content/wdi_data (4).csv")
df.head()

   Unnamed: 0  Year        value  ...      Region Income Group Lending Type
0           0  2015  2087.305323  ...  South Asia   Low income          IDA
1           1  2016  1981.118069  ...  South Asia   Low income          IDA
2           2  2017  2058.400221  ...  South Asia   Low income          IDA
3           3  2018  2082.635648  ...  South Asia   Low income          IDA
4           4  2019  2152.366489  ...  South Asia   Low income          IDA

[5 rows x 9 columns]

In [46]:
df.sample(10)

      Unnamed: 0  Year  ...         Income Group    Lending Type
16            16  2019  ...  Lower middle income            IBRD
2449        2449  2015  ...          High income  Not classified
4207        4207  2018  ...  Upper middle income           Blend
658          658  2016  ...  Lower middle income             IDA
1021        1021  2020  ...  Upper middle income            IBRD
2708        2708  2016  ...          High income  Not classified
1023        1023  2016  ...  Lower middle income           Blend
2370        2370  2020  ...           Low income             IDA
3818        3818  2019  ...  Lower middle income            IBRD
1064        1064  2017  ...          High income  Not classified

[10 rows x 9 columns]

In [47]:
df_2019= df.query('Year==2019')
df_2019.sample(10)

      Unnamed: 0  Year  ...         Income Group    Lending Type
4268        4268  2019  ...  Upper middle income             IDA
1194        1194  2019  ...          High income  Not classified
2177        2177  2019  ...  Lower middle income            IBRD
2393        2393  2019  ...  Upper middle income            IBRD
1665        1665  2019  ...  Lower middle income             IDA
2333        2333  2019  ...           Low income             IDA
2303        2303  2019  ...  Upper middle income            IBRD
2963        2963  2019  ...          High income            IBRD
1359        1359  2019  ...  Upper middle income            IBRD
316          316  2019  ...  Lower middle income            IBRD

[10 rows x 9 columns]

In [48]:
df_2019 = df_2019.query("indicator in(['SP.DYN.LE00.IN','NY.GDP.PCAP.PP.CD'])")
df_2019

      Unnamed: 0  Year  ...         Income Group    Lending Type
4              4  2019  ...           Low income             IDA
10            10  2019  ...  Upper middle income            IBRD
16            16  2019  ...  Lower middle income            IBRD
22            22  2019  ...  Lower middle income            IBRD
28            28  2019  ...          High income            IBRD
...          ...   ...  ...                  ...             ...
2122        2122  2019  ...          High income  Not classified
2127        2127  2019  ...  Lower middle income  Not classified
2132        2132  2019  ...           Low income             IDA
2137        2137  2019  ...  Lower middle income             IDA
2142        2142  2019  ...  Lower middle income           Blend

[390 rows x 9 columns]

In [49]:
df_2019.drop(columns=["Unnamed: 0","Year"], inplace= True)
df_2019.head()

           value          indicator  ...         Income Group Lending Type
4    2152.366489  NY.GDP.PCAP.PP.CD  ...           Low income          IDA
10  14230.989507  NY.GDP.PCAP.PP.CD  ...  Upper middle income         IBRD
16  11997.337834  NY.GDP.PCAP.PP.CD  ...  Lower middle income         IBRD
22   6952.419362  NY.GDP.PCAP.PP.CD  ...  Lower middle income         IBRD
28  22460.019253  NY.GDP.PCAP.PP.CD  ...          High income         IBRD

[5 rows x 7 columns]

In [53]:
df_pivot = df_2019.pivot(index=['Country Code','Country Name','Region','Income Group','Lending Type'],columns ='indicator',values = 'value').reset_index()
df_pivot.head()

indicator Country Code          Country Name  ... NY.GDP.PCAP.PP.CD SP.DYN.LE00.IN
0                  ABW                 Aruba  ...               NaN         76.293
1                  AFG           Afghanistan  ...       2152.366489         64.833
2                  AGO                Angola  ...       6952.419362         61.147
3                  ALB               Albania  ...      14230.989507         78.573
4                  ARE  United Arab Emirates  ...      69957.618075         77.972

[5 rows x 7 columns]

In [54]:
df_pivot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country Code       208 non-null    object
 1   Country Name       208 non-null    object
 2   Region             208 non-null    object
 3   Income Group       208 non-null    object
 4   Lending Type       208 non-null    object
 5   NY.GDP.PCAP.PP.CD  192 non-null    float64
 6   SP.DYN.LE00.IN     198 non-null    float64
dtypes: float64(2), object(5)
memory usage: 11.5+ KB

In [57]:
fig = px.scatter(
    df_pivot,
    x= "NY.GDP.PCAP.PP.CD",
    y= "SP.DYN.LE00.IN",
    title= "Health vs Wealth",
    labels= {"SP.DYN.LE00.IN":"Life Expectency","NY.GDP.PCAP.PP.CD":"GDP Per Capita Income"},
    color = "Region"

)

fig.show()